spring:
  application:
    name: oauth2-login
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - profile
              - email
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      timeout: 6000
    session:
      store-type: redis
      timeout: 7d

server:
  port: 8080 